### ISSUE TITLE
build failed on Vercel

### ISSUE THREAD

**Issue by screensaversclub** [screensavers-club/argos-docs#11]
> 15:34:57.032 | [success] [webpackbar] Client: Compiled with some errors in 6.07s
-- | --
15:34:57.039 | Error: Image static/img/v1-0/1-0-1.jpg used in docs/hardware/versions/v1-0.md not found.
15:34:57.039 | at async Promise.all (index 0)
15:34:57.040 | Error: Image static/img/v1-2/1-2-1.jpg used in docs/hardware/versions/v1-2.md not found.
15:34:57.040 | at async Promise.all (index 0)
15:34:57.040 | Client bundle compiled with errors therefore further build is impossible.

**Comment by screensaversclub** [comment]
Try renaming all the images to be lowercase (currently extensions are uppercase on Github repo)

**Comment by bananaleow** [comment]
solved with https://stackoverflow.com/a/23609455
